import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'node:path';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 5173,
    host: true,
    strictPort: false,
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:3025',
        changeOrigin: false,
        ws: false,
      },
    },
  },
  build: {
    target: 'es2022',
    sourcemap: true,
    rollupOptions: {
      output: {
        manualChunks: {
          'react-vendor': ['react', 'react-dom'],
          markdown: ['react-markdown', 'remark-gfm', 'rehype-highlight'],
        },
      },
    },
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icons/*.png', 'favicon.png', 'icons/*.svg'],
      manifest: {
        // `id` REQUIRED on Android 14+ for clean WebAPK install (no
        // Chrome badge). The v=… bump forces Chrome to recompile a
        // fresh WebAPK with the current targetSdkVersion — Android 16
        // refuses installation of stale WebAPKs with "fatto con
        // versione precedente di Android". Bump this string whenever
        // Google moves the WebAPK targetSdk forward, or after a long
        // period without manifest changes.
        id: '/?source=pwa&v=2026-05',
        name: 'cozza-ai · cockpit',
        short_name: 'cozza-ai',
        description: 'Personal cockpit AI for Viture Beast XR — chat & voice',
        theme_color: '#000000',
        background_color: '#000000',
        display: 'standalone',
        // display_override gives Android 14+ a richer install signal
        // and avoids the "browser fallback" pill that some launchers
        // show next to non-trusted PWAs.
        display_override: ['standalone', 'minimal-ui', 'browser'],
        orientation: 'any',
        start_url: '/?source=pwa&v=2026-05',
        scope: '/',
        dir: 'ltr',
        lang: 'it',
        categories: ['productivity', 'utilities'],
        // Explicit: this is a standalone PWA, not a wrapper around a
        // Play Store app. Required false on Android 14+ to enable
        // rich install dialog.
        prefer_related_applications: false,
        // Pixel 10a / Android 16 "rich install UI" needs at least one
        // wide screenshot (form_factor=wide) and one mobile screenshot.
        // The /icons/screenshot-*.png are generated by scripts/generate-icons.mjs.
        screenshots: [
          {
            src: '/icons/screenshot-mobile.png',
            sizes: '1080x1920',
            type: 'image/png',
            form_factor: 'narrow',
            label: 'Chat AI con voce e generazione immagini',
          },
          {
            src: '/icons/screenshot-wide.png',
            sizes: '1920x1080',
            type: 'image/png',
            form_factor: 'wide',
            label: 'Cockpit HUD con telemetria multi-progetto',
          },
        ],
        // Icons MUST include both `any` and `maskable` purposes as
        // separate entries — Chrome refuses to install a clean WebAPK
        // (no badge) without dedicated maskable icons.
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: '/icons/icon-192-maskable.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: '/icons/icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
        shortcuts: [
          {
            name: 'Admin',
            short_name: 'Admin',
            description: 'Pannello di controllo',
            url: '/admin',
          },
          {
            name: 'Cockpit HUD',
            short_name: 'Cockpit',
            description: 'Plancia di comando 25+ progetti',
            url: '/cockpit/',
          },
          {
            name: 'Remote',
            short_name: 'Remote',
            description: 'Trackpad / D-pad / voice',
            url: '/cockpit/remote/',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,woff,woff2}'],
        // Heavy lazy-loaded chunks: cached on first use, NOT precached, so
        // the install bundle stays slim on mobile networks.
        globIgnores: [
          '**/mermaid*',
          '**/cytoscape*',
          '**/architectureDiagram*',
          '**/wardley*',
          '**/katex*',
        ],
        maximumFileSizeToCacheInBytes: 1_500_000,
        navigateFallback: '/index.html',
        // The chat PWA's service worker scope is `/`, so by default it would
        // intercept navigations to `/cockpit/*` and serve the chat shell.
        // Deny these paths so the browser fetches the cockpit dist/ directly.
        navigateFallbackDenylist: [/^\/cockpit\//, /^\/admin/],
        // Auto-activate the new SW immediately so installed PWAs always get
        // the latest bundle on next load. Without this, mobile users would
        // sit on a stale cached version until they manually clear caches.
        skipWaiting: true,
        clientsClaim: true,
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          // Lazy chunks: cache on first fetch
          {
            urlPattern: /\/assets\/(mermaid|cytoscape|architectureDiagram|wardley|katex)[^/]*\.js$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'lazy-chunks-cache',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 30 },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
          {
            urlPattern: ({ url }) => url.pathname.startsWith('/api/'),
            handler: 'NetworkOnly',
          },
        ],
      },
      devOptions: {
        enabled: false,
      },
    }),
  ],
});
