#!/usr/bin/env node
/**
 * Generate PWA PNG icons from the brand SVGs.
 *
 *   node scripts/generate-icons.mjs
 *
 * Output:
 *   apps/web/public/icons/icon-192.png       (any)
 *   apps/web/public/icons/icon-512.png       (any)
 *   apps/web/public/icons/icon-192-maskable.png
 *   apps/web/public/icons/icon-512-maskable.png
 *   apps/web/public/icons/apple-touch-icon.png  (180x180, any)
 *   apps/web/public/favicon.ico                  (32x32 + 16x16)
 *
 * Requires `sharp` (will pnpm-add it on first run if missing).
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

let sharp;
try {
  sharp = (await import('sharp')).default;
} catch {
  console.warn('▶ Installing sharp (one-time)…');
  execSync('pnpm add -D -w sharp', { stdio: 'inherit', cwd: ROOT });
  sharp = (await import('sharp')).default;
}

const OUT_DIR = join(ROOT, 'apps/web/public/icons');
mkdirSync(OUT_DIR, { recursive: true });

const ANY_SVG = readFileSync(join(ROOT, 'assets/logo.svg'));
const MASK_SVG = readFileSync(join(ROOT, 'assets/logo-maskable.svg'));

const tasks = [
  { svg: ANY_SVG, size: 192, file: 'icon-192.png' },
  { svg: ANY_SVG, size: 512, file: 'icon-512.png' },
  { svg: MASK_SVG, size: 192, file: 'icon-192-maskable.png' },
  { svg: MASK_SVG, size: 512, file: 'icon-512-maskable.png' },
  { svg: ANY_SVG, size: 180, file: 'apple-touch-icon.png' },
];

for (const t of tasks) {
  const out = join(OUT_DIR, t.file);
  await sharp(t.svg).resize(t.size, t.size).png({ compressionLevel: 9 }).toFile(out);
  console.warn(`  ✓ ${t.file} (${t.size}x${t.size})`);
}

// Favicon — copy 32x32 PNG as favicon.png + the same as ico fallback for older browsers
const FAVICON_PNG = join(ROOT, 'apps/web/public/favicon.png');
await sharp(ANY_SVG).resize(64, 64).png({ compressionLevel: 9 }).toFile(FAVICON_PNG);
console.warn('  ✓ favicon.png (64x64)');

console.warn('\nDone. Add these to your manifest if not already there.');

// Drop a note alongside
writeFileSync(
  join(OUT_DIR, 'GENERATED.txt'),
  `Generated by scripts/generate-icons.mjs from assets/logo.svg + assets/logo-maskable.svg.\nDo not commit: regenerate when the brand SVG changes.\n`,
);
